### ISSUE TITLE
Could not locate the character `?' in the following fonts: ChineseFonts, ChineseFonts

### ISSUE THREAD

**Issue by KevinBlandy** [someok/asciidoctor-gradle-example#1]
按照您的方法进行了配置，执行：`gradle asciidoctorPdf` 命令后出现异常。

配置：

![image](https://user-images.githubusercontent.com/17979625/206954032-86423af1-3a4c-4f5b-adb3-d361fe48fffa.png)

异常信息：

```txt
> Task :spring-boot-project:spring-boot-docs:asciidoctorPdf
12月 12, 2022 11:24:37 上午 uri:classloader:/gems/prawn-2.2.2/lib/prawn/font.rb save_font
警告: Could not locate the character `?' in the following fonts: ChineseFonts, ChineseFonts
12月 12, 2022 11:24:45 上午 uri:classloader:/gems/asciidoctor-pdf-1.5.3/lib/asciidoctor/pdf/converter.rb traverse_list_item
警告: Could not locate the character `?' in the following fonts: ChineseFonts, ChineseFonts
12月 12, 2022 11:24:47 上午 uri:classloader:/gems/spring-asciidoctor-backends-0.0.0/lib/spring-asciidoctor-backends/spring-pdf-converter.rb convert_listing_or_literal   
警告: Could not locate the character `
' in the following fonts: Monospace, ChineseFonts
12月 12, 2022 11:24:49 上午 uri:classloader:/gems/prawn-table-0.2.2/lib/prawn/table/cell/text.rb with_font
警告: Could not locate the character ` ' in the following fonts: ChineseFonts, ChineseFonts
12月 12, 2022 11:25:24 上午 uri:classloader:/gems/asciidoctor-2.0.12/lib/asciidoctor/document.rb content
警告: Could not locate the character `?' in the following fonts: ChineseFonts, ChineseFonts
Exception in thread "main" org.asciidoctor.gradle.remote.AsciidoctorRemoteExecutionException: ERROR: The following messages from AsciidoctorJ are treated as errors:
Could not locate the character `?' in the following fonts: ChineseFonts, ChineseFonts
- Could not locate the character `?' in the following fonts: ChineseFonts, ChineseFonts
- Could not locate the character ` ' in the following fonts: ChineseFonts, ChineseFonts
- Could not locate the character `?' in the following fonts: ChineseFonts, ChineseFonts
        at org.asciidoctor.gradle.remote.ExecutorBase.failOnWarnings(ExecutorBase.groovy:229)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure3.doCall(AsciidoctorJavaExec.groovy:76)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec$_run_closure3.call(AsciidoctorJavaExec.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2358)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2343)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2384)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:68)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:49)
```

您有遇到此类问题吗？

我的gradle版本：

```txt

------------------------------------------------------------
Gradle 7.5.1
------------------------------------------------------------

Build time:   2022-08-05 21:17:56 UTC
Revision:     d1daa0cbf1a0103000b71484e1dbfe096e095918

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17 (Oracle Corporation 17+35-LTS-2724)
OS:           Windows 10 10.0 amd64
```

**Comment by someok** [comment]
这个我没遇到过，我之前一直是在 Mac 上运行的，没在 Windows 上搞过，不知道是不是有差异
